# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1e661989e894381aadf63facb5bcfc837e003f116a07c10fdc0df5ffe31297007f22443267e9433183182f463bc83941f0dfec0ea73a8f084c34b22074b3b46

test:
  secret_key_base: 25d4ea2b1648fbfe2086324c5cf68ff87e8a4d2c5fd16a81de3ce3f127166321204332af423527cc51df4af16a44e9f8eed3c3fa0ccd3bfb6a51679407a0150a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
